### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by realedk**
Added updated images and Firefox tutorial

### CODE REVIEW

**Comment by RockSolid1106** [comment]
Is your file old? You're having v0.8.5 changelogs for some reason when 0.8.6 is already released

**Comment by realedk** [comment]
No, it's a direct merge. I'll fix it.

**Comment by RockSolid1106** [comment]
So you'll get a new pull req? I'll close this one if that's the case

**Comment by realedk** [comment]
Yeah, I'll open a new one.

-closed-

**Pull request closed without merging**
