### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by EDKTech**
Added instructions on installing in Edge (I hope I'm not intruding)

### CODE REVIEW

**Comment by RockSolid1106** [comment]
Thanks, but I'll add that when the latest version with the new logos is approved on the edge store. Should be approved my tomorrow.

**Review by RockSolid1106 — APPROVED** [review]

**Comment by EDKTech** [comment]
Sounds good! Are you going to update the manual install extension for Chrome?

**Comment by RockSolid1106** [comment]
> Sounds good! Are you going to update the manual install extension for Chrome?

The installation process doesn't change for Chrome? Not sure if I understand what you mean.

**Comment by RockSolid1106** [comment]
Changes were added separately since the file was quite a few commits behind. Request closed.

**Pull request closed without merging**
